### ISSUE TITLE
How can I add Context Actions?

### ISSUE THREAD

**Issue by katatunix** [TimLariviere/FabulousContacts#15]
Hello,

I want to add some Context Actions for each contact in the ContactsListPage. From the [document](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/interactivity#Context_Actions) of Xamarin.Forms ListView, it supports Context Actions. But I don't know how to apply it to Fabulous.

Please help, thanks in advanced.

**Comment by TimLariviere** [comment]
Ah yes, it's not possible currently in Fabulous, as we don't give access to the created ViewCell.
https://github.com/fsprojects/Fabulous/blob/04b8c6aebfc09427352cefe60b29fccea350d15b/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/CustomControls.fs#L110-L111

Could you open an issue for that on https://github.com/fsprojects/Fabulous, please?

**Comment by TimLariviere** [comment]
This has been fixed in Fabulous.XamarinForms 0.50
