### ISSUE TITLE
Detected package downgrade. FSharp.Core from 4.6.2 to 4.5.2

### ISSUE THREAD

**Issue by luizperes** [TimLariviere/FabulousContacts#16]
This is a known issue for VSMac and the workaround is on https://github.com/mono/monodevelop/pull/5137

<img width="358" alt="Screen Shot 2019-08-05 at 1 06 09 PM" src="https://user-images.githubusercontent.com/6173065/62491885-03451000-b782-11e9-946b-313d996d0259.png">

**Comment by TimLariviere** [comment]
Fixed by #17
