### ISSUE TITLE
README instructions omit steps.

### ISSUE THREAD

**Issue by InTEGr8or** [TimLariviere/FabulousContacts#23]
I'm trying to use this example because I'm new to the dev env.

So when it says "Once you have a key, simply replace REPLACE_WITH_GOOGLE_API_KEY in the keys.xml file in the Android project" as the last item in the instructions, I feel like there might be another step or two there that are not mentioned for people already familiar with the dev env.

Something like `dotnet build` or `dotnet run` or something, but I don't see it anywhere. How do I run it?

**Comment by TimLariviere** [comment]
The README is not exhaustive in its steps.
I assumed people interested by it would already be somewhat familiar with Xamarin.

In reality, if you already have installed Visual Studio with the Xamarin workload, you only need to open the solution in Visual Studio, replace the key if you want to display the map then build.
Visual Studio will take care of everything else.

In case you need more information, the Microsoft documentation has all the instructions: https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows

**Comment by InTEGr8or** [comment]
I see. I thought something indicated that this might work in vscode/terminal. Maybe I dreamed of the future.

**Comment by TimLariviere** [comment]
I know Microsoft is working on porting Xamarin to .NET 6 and VSCode. But that's only planned for the end of this year.
So that future is not necessarily too far away.
